language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.0

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-28.0.3

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod -R +x gdxmachine-core/src
  - chmod -R +x gdxmachine-platform-desktop/src
  - chmod -R +x gdxmachine-platform-android/src
  - chmod -R +x gdxmachine-sandbox-desktop/src
  - chmod -R +x gdxmachine-sandbox-android/src
  - chmod -R +x gdxmachine-sandbox-source/src
  - chmod +x gradlew

script: ./gradlew clean build